-- 1.
-- If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
-- Find the sum of all the multiples of 3 or 5 below 1000.
{-# OPTIONS_GHC -Wno-incomplete-patterns #-}

sumOfMult n = sum [x | x <- [1 .. (n -1)], x `mod` 3 == 0 || x `mod` 5 == 0]

-- 2.
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

listFib n = go n 1 1
  where
    go n f s
      | (f + s) > n = []
      | otherwise = if even (f + s) then (f + s) : go n s (f + s) else go n s (f + s)

-- 3.
-- The prime factors of 13195 are 5, 7, 13 and 29.
-- What is the largest prime factor of the number 600851475143 ? -Don't try this. Will never end LOL
-- Reuse isPrime function from slides
isPrime n = ip n [2 .. (n `div` 2)]
  where
    ip _ [] = True
    ip n (x : xs)
      | n `mod` x == 0 = False
      | otherwise = ip n xs

-- factors n = [x | x <- [1 .. n], n `mod` x == 0]

largestPrimeFactor n = maximum [x | x <- [1 .. n], isPrime x, n `mod` x == 0]

-- 4.
-- A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
-- Find the largest palindrome made from the product of two 3-digit numbers.
isPalindrome x = show x == reverse (show x)

largestPalindrome = maximum [x * y | x <- [1 .. 999], y <- [1 .. 999], isPalindrome (x * y)]

-- 5.
-- 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
-- What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

isDivisibleBy1ToN number n = go number [1 .. n]
  where
    go number (x : xs)
      | null xs = True
      | number `mod` x /= 0 = False
      | otherwise = go number xs

-- Smallest number divisible by 1..n
smallest n = go n 1
  where
    go n i
      | isDivisibleBy1ToN i n = i
      | otherwise = go n (i + 1)


-- 7.
-- By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
-- What is the 10 001st prime number?
nthPrimeNumber n = [ x | x <-[1..], isPrime x] !! n


-- 8. Too tired to give it a thought now

-- 9. 
-- A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2
-- For example, 32 + 42 = 9 + 16 = 25 = 52.
-- There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc.

pitagoreanTriple = [(a, b, c) | c <- [1 .. 1000], b <- [1 .. c], a <- [1 .. b], a^2 + b^2 == c^2, a + b + c == 1000]
 -- result [(200,375,425)]
pitagoreanTripleProduct = [a * b * c | c <- [1 .. 1000], b <- [1 .. c], a <- [1 .. b], a ^ 2 + b ^ 2 == c ^ 2, a + b + c == 1000]

-- Variable not in scope: name of the var or function. D' you forgot to command + s LOL